version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install --prefix ./app/
      - npm run build --prefix ./app/
      - aws s3 sync s3://ugram-app/ ./app/build/